# Generated by Django 4.0.4 on 2022-05-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.EmailField(default=2, max_length=70),
            preserve_default=False,
        ),
    ]
